import type { Metadata } from "next";
import { Anton } from 'next/font/google'
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"

export const metadata: Metadata = {
  title: "Mudderfuger 🛹🍻",
  description: "Generated by create next app",
};
const anton = Anton({ weight: '400', subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={anton.className}>
      <head>
        <link rel="icon" href="/icon.ico" type="image/x-icon" sizes="32x32" />
        <link rel="preconnect" href="https://mudderfuger.b-cdn.net" />
        {/* Snipcart loader logic, lazyOnload, runs after DOM is interactive */}
        </head>
      <body>
        {children}
        <SpeedInsights />
        <Analytics/>
      </body>
    </html>
  );
}