import type { Metadata } from "next";
import { Anton } from 'next/font/google'
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: "Mudderfuger 🛹🍻",
  description: "Generated by create next app",
};
const anton = Anton({ weight: '400', subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={anton.className}>
      <body>
        {children}
      </body>
    </html>
  );
}