import type { MetadataRoute } from 'next'

const SITE = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://mudderfuger.ai'

/**
 * robots.txt — generated by Next's App Router at /robots.txt
 *
 * NOTE: /products/* is deliberately NOT disallowed here, for two reasons:
 *
 * 1. Those pages are Snipcart's server-side validation targets. Snipcart
 *    fetches them directly to verify price and custom fields — blocking
 *    them would be pointless (it ignores robots.txt) but it costs nothing
 *    to be explicit about leaving them reachable.
 *
 * 2. More importantly: robots.txt Disallow PREVENTS de-indexing. A blocked
 *    URL can't be crawled, so Google never sees the `noindex` and the URL
 *    can sit in the index indefinitely as a bare listing. The noindex lives
 *    in products/layout.tsx instead, and crawlers must be able to reach it
 *    to obey it.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
    },
    sitemap: `${SITE}/sitemap.xml`,
    host: SITE,
  }
}
